In [4]:
import os
import config  # 假设config模块已正确定义和导入
print(os.getcwd())

for root, dirs, files in os.walk(os.getcwd()):
    # root 是当前目录的路径
    print(f"当前目录: {root}")
    
    # dirs 是当前目录下的所有子目录列表
    for dir in dirs:
        print(f"子目录: {os.path.join(root, dir)}")
    
    # files 是当前目录下的所有文件列表
    for file in files:
        print(f"文件: {os.path.join(root, file)}")

d:\yangkeyin\datasets\251010清华数据分析
当前目录: d:\yangkeyin\datasets\251010清华数据分析
子目录: d:\yangkeyin\datasets\251010清华数据分析\acute
子目录: d:\yangkeyin\datasets\251010清华数据分析\utils
子目录: d:\yangkeyin\datasets\251010清华数据分析\__pycache__
文件: d:\yangkeyin\datasets\251010清华数据分析\config.py
文件: d:\yangkeyin\datasets\251010清华数据分析\demo.ipynb
文件: d:\yangkeyin\datasets\251010清华数据分析\process_rhd_files.py
文件: d:\yangkeyin\datasets\251010清华数据分析\process_rhd_to_fif.py
文件: d:\yangkeyin\datasets\251010清华数据分析\simple_rhd_reader.py
当前目录: d:\yangkeyin\datasets\251010清华数据分析\acute
子目录: d:\yangkeyin\datasets\251010清华数据分析\acute\20250612
子目录: d:\yangkeyin\datasets\251010清华数据分析\acute\20250701
子目录: d:\yangkeyin\datasets\251010清华数据分析\acute\20250702
当前目录: d:\yangkeyin\datasets\251010清华数据分析\acute\20250612
子目录: d:\yangkeyin\datasets\251010清华数据分析\acute\20250612\beard_fast
子目录: d:\yangkeyin\datasets\251010清华数据分析\acute\20250612\beard_slow
子目录: d:\yangkeyin\datasets\251010清华数据分析\acute\20250612\visual
子目录: d:\yangkeyin\datasets\251010清华数据分

KeyboardInterrupt: 

In [13]:
import numpy as np

# 假设已经有result和next_result这两个字典，并且它们的结构正确
# 这里为了示例，简单创建两个包含amplifier_data的字典
result = {'amplifier_data': np.array([[1, 2, 3],[1,2,3]])}
next_result = {'amplifier_data': np.array([[4, 5, 6],[4,5,6]])}

result['amplifier_data'] = np.hstack((
    result['amplifier_data'], 
    next_result['amplifier_data'],  
))
print(result['amplifier_data'])

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [15]:
# 假设parent_dir_contents是一个包含文件名的列表
parent_dir_contents = ["file1.txt", "file2.txt", "file3.txt"]
filename = "file1.txt"

try:
    # 尝试获取filename在parent_dir_contents列表中的索引
    index = parent_dir_contents.index(filename)
    print(f"{filename} 在列表中的索引是: {index}")
except ValueError:
    # 如果filename不在列表中，捕获ValueError异常并打印提示信息
    print(f"{filename} 不在列表中")


file1.txt 在列表中的索引是: 0


In [20]:
import os
import sys

# 将当前文件的上级目录的上级目录添加到系统路径中
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath('utils/rhd_event_extractor.py'))))

print(os.path.abspath('utils/rhd_event_extractor.py'))

# 展现当前系统路径
print(sys.path)

d:\yangkeyin\datasets\251010清华数据分析\utils\rhd_event_extractor.py
['d:\\appinstall\\anaconda\\envs\\neurosort\\python39.zip', 'd:\\appinstall\\anaconda\\envs\\neurosort\\DLLs', 'd:\\appinstall\\anaconda\\envs\\neurosort\\lib', 'd:\\appinstall\\anaconda\\envs\\neurosort', '', 'd:\\appinstall\\anaconda\\envs\\neurosort\\lib\\site-packages', 'd:\\appinstall\\anaconda\\envs\\neurosort\\lib\\site-packages\\win32', 'd:\\appinstall\\anaconda\\envs\\neurosort\\lib\\site-packages\\win32\\lib', 'd:\\appinstall\\anaconda\\envs\\neurosort\\lib\\site-packages\\Pythonwin', 'd:\\yangkeyin\\datasets', 'd:\\yangkeyin\\datasets', 'd:\\yangkeyin\\datasets\\251010清华数据分析', 'd:\\yangkeyin\\datasets\\251010清华数据分析']


In [21]:
import numpy as np

# 假设 all_digital_data 是一个包含多个数字数组的列表
# 示例 all_digital_data
all_digital_data = [np.array([1, 2, 3]), np.array([4, 5, 6])]

concatenated_digital = np.concatenate(all_digital_data)
print(concatenated_digital)

[1 2 3 4 5 6]


In [25]:
import numpy as np

# 假设已经有一个名为diff的numpy数组
# 例如
diff = np.array([0, 1, 1, 0, 1])
diff = np.diff(diff.astype(int))
print(diff)

# 使用np.where函数找出diff中值为1的元素的索引
indices = np.where(diff == 1)[0]

print(indices)

[ 1  0 -1  1]
[0 3]
